name: Fix Price scraper workflow

on: push

jobs:
  send_message:
    runs-on: ubuntu-latest
    steps:
      - name: Send message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: Fix Price Scraper workflow executed successfully.
